name: situraja_village_app
description: Explore Situraja village application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  another_flushbar: ^1.12.3
  flutter_svg: ^2.0.7
  
  # Added for API Integration
  provider: ^6.1.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  html: ^0.15.6
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Alatsi
      fonts:
        - asset: assets/fonts/Alatsi-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/